apiVersion: apps/v1
kind: Deployment
metadata:
  name: coubee-be-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coubee-be-user
  template:
    metadata:
      labels:
        app: coubee-be-user
    spec:
      containers:
        - name: coubee-be-user
          image: mingyoolee/coubee-be-user:0.0.1
          imagePullPolicy: IfNotPresent  # Changed from Always to IfNotPresent for local development
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: stg
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/config
              name: be-user-config-volume
            - mountPath: /etc/secret
              name: be-user-secret-volume
          # Add resource limits and requests
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          # Add health checks
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: be-user-config-volume
          configMap:
            name: be-user-config
            items:
              - key: application-stg.yml
                path: application-stg.yml
        - name: be-user-secret-volume
          secret:
            secretName: be-user-secret
            items:
              - key: application-secret.yml
                path: application-secret.yml