apiVersion: v1
kind: ConfigMap
metadata:
  name: be-user-config
data:
  application-stg.yml: |
    server:
      port: 8080

    # Actuator의 liveness/readiness probe 엔드포인트를 활성화하는 설정
    management:
      endpoint:
        health:
          probes:
            enabled: true
      health:
        readiness-state:
          enabled: true
        liveness-state:
          enabled: true
    
    spring:
      datasource:
        url: jdbc:postgresql://52.78.117.85:5432/coubee_user
        driver-class-name: org.postgresql.Driver
        hikari:
          connection-test-query: SELECT 1
          validation-timeout: 5000

      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          # 기존 DB를 삭제하지 않고 엔티티와 스키마가 일치하는지 검사만 하도록 변경
          ddl-auto: validate
        # 'validate' 모드에서는 이 옵션이 필요 없습니다.
        # generate-ddl: true
        show-sql: true
        open-in-view: false
        properties:
          hibernate.default_schema: coubee_user
      kafka:
        bootstrap-servers: coubee-external-kafka-service:9092
        
    file:
      upload:
        base-dir: ${user.home}/Desktop/coubee-img
        resource-url: /images/**
