apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  application-stg.yml: |
    server:
      port: 8080

    spring:
      cloud:
        gateway:
          # ==========================================================
          # ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼ 이 부분 추가 ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
          # Gateway 레벨에서 전역 CORS 설정을 추가합니다.
          globalcors:
            cors-configurations:
              '[/**]': # 모든 경로(/**)에 대해 적용
                allowedOrigins: # '*' 대신 명시적인 URL 사용
                  - "http://127.0.0.1:5500"
                  - "http://localhost:5500"
                  - "http://127.0.0.1:5501"
                  - "http://localhost:5501"
                  - "http://127.0.0.1:3000"
                  - "http://localhost:3000"
                allowedMethods:
                  - "GET"
                  - "POST"
                  - "PUT"
                  - "DELETE"
                  - "PATCH"
                  - "OPTIONS"
                allowedHeaders: "*"
                allowCredentials: true
          # ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲ 위 부분 추가 ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲
          # ==========================================================
          server:
            webmvc:
              routes:
                - id: coubee-be-user 
                  uri: http://coubee-be-user-service:8080
                  predicates:
                    - Path=/api/user/**
                  filters:
                    - addAuthenticationHeader
                - id: coubee-be-store
                  uri: http://coubee-be-store-service:8080
                  predicates:
                    - Path=/api/store/**
                  filters:
                    - addAuthenticationHeader
                - id: coubee-be-product
                  uri: http://coubee-be-product-service:8080
                  predicates:
                    - Path=/api/product/**
                  filters:
                    - addAuthenticationHeader
                - id: coubee-be-order
                  uri: http://coubee-be-order-service:8080
                  predicates:
                    - Path=/api/order/**
                  filters:
                    - addAuthenticationHeader