apiVersion: v1
data:
  application-stg.yml: "server:\n  port: 8080\n\nspring:\n  cloud:\n    gateway:\n
    \     server:\n        webmvc:\n          routes:\n            - id: coubee-be-user
    \n              uri: http://coubee-be-user-service:8080\n              predicates:\n
    \               - Path=/api/user/**\n              filters:\n                -
    addAuthenticationHeader\n            - id: coubee-be-store\n              uri:
    http://coubee-be-store-service:8080\n              predicates:\n                -
    Path=/api/store/**\n              filters:\n                - addAuthenticationHeader\n
    \           - id: coubee-be-product\n              uri: http://coubee-be-product-service:8080\n
    \             predicates:\n                - Path=/api/product/**\n              filters:\n
    \               - addAuthenticationHeader\n            - id: coubee-be-order\n
    \             uri: http://coubee-be-order-service:8080\n              predicates:\n
    \               - Path=/api/order/**\n              filters:\n                -
    addAuthenticationHeader\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"application-stg.yml":"server:\n  port: 8080\n\nspring:\n  cloud:\n    gateway:\n      server:\n        webmvc:\n          routes:\n            - id: coubee-be-user \n              uri: http://coubee-be-user-service:8080\n              predicates:\n                - Path=/api/user/**\n              filters:\n                - addAuthenticationHeader\n            - id: coubee-be-store\n              uri: http://coubee-be-store-service:8080\n              predicates:\n                - Path=/api/store/**\n              filters:\n                - addAuthenticationHeader\n            - id: coubee-be-product\n              uri: http://coubee-be-product-service:8080\n              predicates:\n                - Path=/api/product/**\n              filters:\n                - addAuthenticationHeader\n            - id: coubee-be-order\n              uri: http://coubee-be-order-service:8080\n              predicates:\n                - Path=/api/order/**\n              filters:\n                - addAuthenticationHeader\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"api-gateway-config","namespace":"default"}}
  creationTimestamp: "2025-08-01T04:55:47Z"
  name: api-gateway-config
  namespace: default
  resourceVersion: "2374"
  uid: 1df50490-c0ba-4c8a-9c47-c038dd70ea23
