# Spring Boot Kafka 설정 예제
spring:
  kafka:
    # Kubernetes 내부 Kafka 서버 주소
    bootstrap-servers: kafka-headless.kafka.svc.cluster.local:9092
    
    # Producer 설정
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        acks: all
        retries: 3
        
    # Consumer 설정
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        
    # Listener 설정
    listener:
      ack-mode: manual_immediate
      concurrency: 3
      
# 토픽 설정 예제
kafka:
  topics:
    user-created: user-created-topic
    order-created: order-created-topic
    payment-completed: payment-completed-topic 